### PR TITLE
Fix using assert_eq

### LINKED ISSUE #134: assert_eq! does not introduce a proof obligation
`assert_eq!(a, b)` should behave the same as `assert!(a == b)`.

## steps to reproduce

```rust
pub fn foo() {
    let a = 1;
    let b = 2;
    assert_eq!(a, b);
}
```

```
./x.py run --bin prusti-rustc -- --edition=2021
```

## expected behavior
*verification error*

## actual behavior
*verification success*

##

This might be resolved by adding this snippet to prusti-contracts/prusti-contracts/src/core_spec/mod.rs
```rust
#[extern_spec(core::panicking)]
#[requires(false)]
#[pure]
pub fn assert_failed<T, U>(
    kind: core::panicking::AssertKind,
    left: &T,
    right: &U,
    args: Option<core::fmt::Arguments<'_>>,
) -> !
where
    T: core::fmt::Debug + ?Sized,
    U: core::fmt::Debug + ?Sized;
 ```

### PR DESCRIPTION
**Pull request by ThomasMayerl**
This PR fixes #134 by requiring false as a precondition for assert_failed (similar to panic)

### CODE REVIEW

**Comment by HSMF** [comment]
Weirdness happens when the arguments are constants. Probably not caused by this PR though:

```rs
fn fail() {
    assert_eq!(1, 2);
}
```

File: prusti-encoder/src/encoders/const.rs [hunk 1]
```diff
@@ -87,22 +88,40 @@ impl ConstEnc {
                         GlobalAlloc::Function { .. } => todo!(),
                         GlobalAlloc::VTable(_, _) => todo!(),
                         GlobalAlloc::Static(_) => todo!(),
-                        GlobalAlloc::Memory(_mem) => {
-                            // If the `unwrap` ever panics we need a different way to get the inner type
```
Comment (Aurel300) [inline prusti-encoder/src/encoders/const.rs:91]: Doesn't this comment still apply?

File: prusti-encoder/src/encoders/const.rs [hunk 2]
```diff
@@ -87,22 +88,40 @@ impl ConstEnc {
...
+                            let rel_addr =
+                                ((alloc_id.get() as u128) << 64) | offset.bytes() as u128;
+
+                            kind.expect_immref().prim_to_snap(
+                                (addr_to_ref)(
+                                    vcx.mk_const_expr(vir::ConstData::Int(rel_addr))
+                                        .downcast_ty(),
+                                ),
+                                ((inner_kind.prim_to_snap)(vcx.mk_const_expr(
+                                    vir::ConstData::Int(bytes.to_bits(mem.0.0.size()).unwrap()),
```
Comment (Aurel300) [inline prusti-encoder/src/encoders/const.rs]: Is this hard-coded for integers? What happens with other scalar types? What about ADT constants?

File: prusti-encoder/src/encoders/const.rs (hunk 1 above)
Comment (ThomasMayerl) [reply prusti-encoder/src/encoders/const.rs:91]: The unwrap below that retrieves the bytes of the allocation can also fail. @JonasAlaif came to the conclusion that this should be a separate PR, though. Should I add comments again?

File: prusti-encoder/src/encoders/const.rs (hunk 2 above)
Comment (ThomasMayerl) [reply prusti-encoder/src/encoders/const.rs]: I discussed this with @JonasAlaif and I will make the call recursive that we can use the same encoding for the inner values. I'll add this to this PR shortly

File: prusti-encoder/src/encoders/const.rs (hunk 1 above)
Comment (JonasAlaif) [reply prusti-encoder/src/encoders/const.rs:91]: @ThomasMayerl yes let's keep this comment: it might not be either of us that has to come back and make this work, so let's make the work easier for that person. So it would also be good to extend this comment with the fact that we saw the unwrap failing when it's a ZST.

**Comment by JonasAlaif** [comment]
@ThomasMayerl one last thing: 110 tests fail here, while only 107 fail on the main branch. Could you check the diff of failing tests and double check that there isn't a regression
