### PR TITLE
Fix pure encoder for unreachable terminator

### LINKED ISSUE #74: Verification fails with undeclared identifier when adding spec to `PartialOrd::partial_cmp`
## The Problem

When attempting to add specifications to the PartialOrd trait, an issue arises in the encoding of the postcondition for `fn partial_cmp()`. The following postcondition:

```rust
#[ensures(
    match result {
        Some(core::cmp::Ordering::Less) => other.partial_cmp(self) === Some(core::cmp::Ordering::Greater),
        Some(core::cmp::Ordering::Greater) => other.partial_cmp(self) === Some(core::cmp::Ordering::Less),
        Some(core::cmp::Ordering::Equal) => other.partial_cmp(self) === Some(core::cmp::Ordering::Equal),
        None => other.partial_cmp(self) === None,
    }
)]
```

causes Prusti to emit Viper code that references identifiers which are never defined. As a result, verification fails with the following Viper error:

`Constructing the AST has failed: undeclared identifier `_0_4s_0` (program-check.vpr@493.94--493.101)`

## The File

```Rust
use prusti_contracts::*;
use std::cmp::{PartialOrd, Ordering};

#[extern_spec]
trait PartialEq<Rhs>
where
    Rhs: ?Sized,
{
    #[pure]
    fn eq(&self, other: &Rhs) -> bool;

    #[pure]
    fn ne(&self, other: &Rhs) -> bool;
}

#[extern_spec]
trait PartialOrd<Rhs>: PartialEq<Rhs>
where
    Rhs: PartialOrd<Self>,
{
    #[pure]
    #[ensures(
        match result {
            Some(core::cmp::Ordering::Less) => other.partial_cmp(self) === Some(core::cmp::Ordering::Greater),
            Some(core::cmp::Ordering::Greater) => other.partial_cmp(self) === Some(core::cmp::Ordering::Less),
            Some(core::cmp::Ordering::Equal) => other.partial_cmp(self) === Some(core::cmp::Ordering::Equal),
            None => other.partial_cmp(self) === None,
        }
    )]
    fn partial_cmp(&self, other: &Rhs) -> Option<Ordering>;

    #[pure]
    #[ensures(result == matches!(self.partial_cmp(other), Some(core::cmp::Ordering::Less | core::cmp::Ordering::Equal)))]
    #[ensures(result ==> !self.gt(other))]
    #[ensures((matches!(self.partial_cmp(other), Some(_)) && !result) ==> self.gt(other))]
    fn le(&self, other: &Rhs) -> bool;

    #[pure]
    #[ensures(result == matches!(self.partial_cmp(other), Some(core::cmp::Ordering::Less)))]
    #[ensures(result ==> !self.ge(other))]
    #[ensures((matches!(self.partial_cmp(other), Some(_)) && !result) ==> self.ge(other))]
    fn lt(&self, other: &Rhs) -> bool;

    #[pure]
    #[ensures(result == matches!(self.partial_cmp(other), Some(core::cmp::Ordering::Greater | core::cmp::Ordering::Equal)))]
    #[ensures(result ==> !self.lt(other))]
    #[ensures((matches!(self.partial_cmp(other), Some(_)) && !result) ==> self.lt(other))]
    fn ge(&self, other: &Rhs) -> bool;

    #[pure]
    #[ensures(result == matches!(self.partial_cmp(other), Some(core::cmp::Ordering::Greater)))]
    #[ensures(result ==> !self.le(other))]
    #[ensures((matches!(self.partial_cmp(other), Some(_)) && !result) ==> self.le(other))]
    fn gt(&self, other: &Rhs) -> bool;
}


#[pure]
#[requires(min <= max)]
#[ensures(result >= min && result <= max)]
fn generic_clamp<T>(value: T, min: T, max: T) -> T
where
    T: PartialOrd,
{
    if value < min {
        min
    } else if value > max {
        max
    } else {
        value
    }
}

#[trusted]
fn main() {
    let value = 5;
    let min = 1;
    let max = 10;
    let clamped_value = generic_clamp(value, min, max);
}
```
## The run command

I ran it using this command:

```Shell
./x.py build && \
    PRUSTI_DUMP_DEBUG_INFO=true PRUSTI_CHECK_OVERFLOWS=false PRUSTI_PRINT_DESUGARED_SPECS=true PRUSTI_DUMP_VIPER_PROGRAM=true \
    ./x.py run  --bin prusti-rustc --features=vir_debug -- --edition=2021 <FILE_PATH>
```

## Prusti Version:

I worked with  `44140025235731f4fe0fecbfc013df50772b55bf ` on the `rewrite-2023` branch.

One thing which I needed to change to even get that far is adding a `continue;` in `prusti-dev/prusti-encoder/src/encoders/impure/fn_wand.rs:380`  [here](https://github.dev/Aurel300/prusti-dev/blob/44140025235731f4fe0fecbfc013df50772b55bf/prusti-encoder/src/encoders/impure/fn_wand.rs#L375-L384)
```rust
  for pred in rbp {
                let GenericKind::Param(b) = pred.0 else {
                    todo!("region bound pair: {pred:?}");
                };
                let ty::RegionKind::ReEarlyParam(a) = pred.1.kind() else {
                    continue; // added this
                    todo!("region bound pair: {pred:?}");
                };
                insert_edge(IndirectKey::Early(a), IndirectKey::Param(b));
            }

```

### PR DESCRIPTION
**Pull request by JonasAlaif**
Fixes https://github.com/Aurel300/prusti-dev/issues/74

### CODE REVIEW

File: prusti-encoder/src/encoders/mir_pure.rs [hunk 1]
```diff
@@ -9,7 +9,7 @@ use prusti_rustc_interface::{
     span::{def_id::DefId, source_map::Spanned},
     target::abi,
 };
-use std::collections::HashMap;
+use std::{collections::HashMap, fmt};
```
Comment (Aurel300) [inline prusti-encoder/src/encoders/mir_pure.rs:12]: I'm guessing this is an accidental import since the `Debug` impl at the end of the file has `fmt::*` everywhere?

File: prusti-encoder/src/encoders/mir_pure.rs [hunk 2]
```diff
@@ -210,7 +220,7 @@ struct Enc<'vir: 'enc, 'enc> {
     body: &'enc mir::Body<'vir>,
     rev_doms: rev_doms::ReverseDominators,
     deps: &'enc mut TaskEncoderDependencies<'vir, MirPureEnc>,
-    // visited: IndexVec<mir::BasicBlock, bool>,
+    // Always holds the next version to be used for a local.
```
Comment (Aurel300) [inline prusti-encoder/src/encoders/mir_pure.rs]:
```suggestion
    /// Always holds the next version to be used for a local.
```

File: prusti-encoder/src/encoders/mir_pure.rs [hunk 3]
```diff
@@ -1135,7 +1144,13 @@ mod rev_doms {
         pub fn new<'a, 'vir>(blocks: &'a mir::BasicBlocks<'vir>) -> Self {
             let no_succ_blocks = blocks
                 .iter_enumerated()
-                .filter(|(_, data)| data.terminator().successors().next().is_none())
+                .filter(|(_, data)| {
+                    /* The below prevents e.g. a SwitchInt with a branch going to
+                       an Unreachable terminator from having a join point, so do
+                       not treat such terminators as return blocks. */
```
Comment (Aurel300) [inline prusti-encoder/src/encoders/mir_pure.rs]:
```suggestion
                    // The below prevents e.g. a SwitchInt with a branch going to
                    // an Unreachable terminator from having a join point, so do
                    // not treat such terminators as return blocks.
```

Comment (Aurel300) [reply prusti-encoder/src/encoders/mir_pure.rs]: The below being the `matches!`? If so, the commented out `data.terminator()...` should be removed?

File: prusti-encoder/src/encoders/mir_pure.rs [hunk 4]
```diff
@@ -1363,3 +1378,31 @@ pub fn encode_place_element<'vir, 'enc, T: TaskEncoder>(
...
+            initialised: false,
+        }
+    }
+}
+
+impl fmt::Display for Version {
+    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
+        if cfg!(debug_assertions) {
+            assert!(self.initialised);
+            write!(f, "{:?}_s{}_i{}", self.location.block, self.location.statement_index, self.index)
```
Comment (Aurel300) [inline prusti-encoder/src/encoders/mir_pure.rs:1402]: Should the `location` field also only exist conditionally?

File: prusti-encoder/src/encoders/mir_pure.rs (hunk 3 above)
Comment (JonasAlaif) [reply prusti-encoder/src/encoders/mir_pure.rs]: No, it's about the commented out `data.terminator()` - I'm not sure exactly what the correct thing to put there is yet, but I think any terminator which actually exits out of the function in a "controlled" way

File: prusti-encoder/src/encoders/mir_pure.rs (hunk 4 above)
Comment (JonasAlaif) [reply prusti-encoder/src/encoders/mir_pure.rs:1402]: Nah, there's no downside to keeping it and it's simpler than conditional statements in the rest of this file. I just did this because I wasn't sure which fmt is best, so I kept both

File: prusti-encoder/src/encoders/mir_pure.rs (hunk 1 above)
Comment (JonasAlaif) [reply prusti-encoder/src/encoders/mir_pure.rs:12]: What do you mean? The Debug impl at the end which uses the fmt everywhere needs this import? Or you mean I should add it to the end?

File: prusti-encoder/src/encoders/mir_pure.rs (hunk 3 above)
Comment (JonasAlaif) [reply prusti-encoder/src/encoders/mir_pure.rs]: And I use this comment to distinguish it from the line below on purpose

File: prusti-encoder/src/encoders/mir_pure.rs (hunk 1 above)
Comment (Aurel300) [reply prusti-encoder/src/encoders/mir_pure.rs:12]: My bad: I thought `fmt` was top-level for some reason. Never mind :)
